# Generated by Django 2.0.1 on 2018-01-05 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.CharField(max_length=50)),
                ('fecha_hora', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CasoJuridico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_caso', models.CharField(max_length=40)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('n_rol_tibunal', models.CharField(max_length=80)),
                ('estado', models.CharField(max_length=50)),
                ('instancia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_etapa', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('descripcion', models.TextField()),
                ('fecha_termini', models.TimeField()),
                ('estado', models.CharField(max_length=50)),
                ('caso', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='App_Base.CasoJuridico')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraUser',
            fields=[
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='App_Base.EstadoUser')),
            ],
        ),
        migrations.CreateModel(
            name='GastoOficina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_gasto', models.CharField(max_length=25)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gastos_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('gasto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='App_Base.GastoOficina')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='App_Base.ExtraUser')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reunion', models.DateTimeField(auto_now_add=True, unique=True)),
                ('tema_reunion', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(max_length=50)),
                ('observaciones', models.TextField()),
                ('demandante', models.CharField(max_length=100)),
                ('demandado', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='App_Base.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='TemaJuridico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tema', models.CharField(max_length=100)),
                ('materia', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='App_Base.Materia')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('caso_juridico', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='App_Base.CasoJuridico')),
            ],
        ),
        migrations.CreateModel(
            name='UserCaso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caso_juridico', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='App_Base.CasoJuridico')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='App_Base.ExtraUser')),
            ],
        ),
        migrations.CreateModel(
            name='UserReunion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('reunion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='App_Base.Reunion')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='App_Base.ExtraUser')),
            ],
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tema_juridico',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='App_Base.TemaJuridico'),
        ),
        migrations.AddField(
            model_name='extrauser',
            name='tipo',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='App_Base.TipoUser'),
        ),
        migrations.AddField(
            model_name='documentosolicitud',
            name='solicitud',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='App_Base.Solicitud'),
        ),
        migrations.AddField(
            model_name='documentacion',
            name='tema_juridico',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='App_Base.TemaJuridico'),
        ),
        migrations.AddField(
            model_name='casojuridico',
            name='solicitud',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='App_Base.Solicitud'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='etapa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='App_Base.Etapa'),
        ),
    ]
