# Generated by Django 2.0.1 on 2018-01-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Base', '0002_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentacion',
            name='docfile',
            field=models.FileField(default='d', upload_to='documents/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentosolicitud',
            name='docfile',
            field=models.FileField(default='d', upload_to='documents/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
