# Generated by Django 2.0.1 on 2018-01-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Base', '0003_auto_20180113_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentacion',
            name='cliente',
            field=models.CharField(default='rut', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='document/<django.db.models.fields.CharField>/'),
        ),
    ]
