# Generated by Django 2.0.1 on 2018-01-13 20:17

import App_Base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Base', '0004_auto_20180113_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentacion',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to=App_Base.models.generate_path),
        ),
    ]
