# Generated by Django 2.0.1 on 2018-01-13 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Base', '0006_documentacion_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentacion',
            name='nombre',
        ),
    ]
