# Generated by Django 2.0.1 on 2018-01-13 21:27

import App_Base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Base', '0007_remove_documentacion_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentosolicitud',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='demandado',
        ),
        migrations.AddField(
            model_name='documentosolicitud',
            name='rut',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='demandado_direccion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='demandado_nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='demandado_rut',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='demandado_telefono',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentosolicitud',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to=App_Base.models.generate_path),
        ),
    ]
