# Generated by Django 2.0.1 on 2018-01-16 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Base', '0008_auto_20180113_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='demandante',
        ),
    ]
