# Generated by Django 2.0.1 on 2018-01-18 03:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App_Base', '0009_remove_solicitud_demandante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reunion',
            old_name='fecha_reunion',
            new_name='fecha_final',
        ),
        migrations.RenameField(
            model_name='reunion',
            old_name='descripcion',
            new_name='observacion',
        ),
        migrations.AddField(
            model_name='reunion',
            name='color',
            field=models.CharField(default='ffffff', max_length=6),
        ),
        migrations.AddField(
            model_name='reunion',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reunion',
            name='todo_Dia',
            field=models.BooleanField(default=False),
        ),
    ]
