# Generated by Django 2.0.1 on 2018-01-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Base', '0010_auto_20180118_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='url',
            field=models.CharField(default='2', max_length=200),
            preserve_default=False,
        ),
    ]
