# Generated by Django 2.0.1 on 2018-01-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Base', '0012_auto_20180118_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion',
            name='fecha_final',
            field=models.CharField(default=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='fecha_inicio',
            field=models.CharField(default=False, max_length=40),
        ),
    ]
