# Generated by Django 2.0.1 on 2018-01-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Base', '0013_auto_20180118_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='caso_juridico',
            field=models.IntegerField(default=0),
        ),
    ]
