# Generated by Django 2.0.1 on 2018-01-19 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Base', '0014_reunion_caso_juridico'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reunion',
            name='user',
            field=models.ForeignKey(blank=True, default='7', on_delete=django.db.models.deletion.CASCADE, to='App_Base.ExtraUser'),
            preserve_default=False,
        ),
    ]
